/**
 * Write src/hosted/scenario-catalog.ts: the metadata of every client
 * scenario in the registry, so the hosted server can build its matrix
 * without importing every scenario module (see ./catalog.ts).
 *
 *   npm run hosted:bundle-catalog
 *
 * The generated file is committed; catalog.test.ts fails when it drifts
 * from the registry.
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { scenarios } from '../scenarios';
import { scenarioMeta, type ScenarioMeta } from './scenario-meta';

export const CATALOG_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  'scenario-catalog.ts'
);

/** The registry's client scenarios as metadata, in registry order. */
export function registryCatalog(): ScenarioMeta[] {
  return Array.from(scenarios.values(), scenarioMeta);
}

/** The module text; plain JSON, so the output is the same on every run. */
export function renderCatalog(metas: readonly ScenarioMeta[]): string {
  return `// Generated by \`npm run hosted:bundle-catalog\` — do not edit.
// The registry's client scenarios as data (see ./catalog.ts). A test keeps
// it in sync with src/scenarios.

import type { ScenarioMeta } from './scenario-meta';

export const SCENARIO_CATALOG: readonly ScenarioMeta[] = ${JSON.stringify(metas, null, 2)};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const metas = registryCatalog();
  writeFileSync(CATALOG_PATH, renderCatalog(metas));
  console.log(`wrote ${CATALOG_PATH} (${metas.length} scenarios)`);
}
