// Generated by `npm run hosted:bundle-catalog` — do not edit.
// The registry's client scenarios as data (see ./catalog.ts). A test keeps
// it in sync with src/scenarios.

import type { ScenarioMeta } from './scenario-meta';

export const SCENARIO_CATALOG: readonly ScenarioMeta[] = [
  {
    "name": "initialize",
    "description": "Tests MCP client initialization handshake",
    "source": {
      "introducedIn": "2025-06-18",
      "removedIn": "2026-07-28"
    },
    "mcpPath": "",
    "steps": [
      {
        "op": "tools/list"
      }
    ],
    "hostable": true
  },
  {
    "name": "tools_call",
    "description": "Tests calling tools with various parameter types",
    "source": {
      "introducedIn": "2025-06-18"
    },
    "mcpPath": "/mcp",
    "steps": [
      {
        "op": "tools/list"
      },
      {
        "op": "tools/call",
        "name": "add_numbers",
        "arguments": {
          "a": 5,
          "b": 3
        }
      }
    ],
    "hostable": true
  },
  {
    "name": "elicitation-sep1034-client-defaults",
    "description": "Tests client applies default values for omitted elicitation fields (SEP-1034)",
    "source": {
      "introducedIn": "2025-11-25",
      "removedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "steps": [
      {
        "op": "tools/list"
      },
      {
        "op": "tools/call",
        "name": "test_client_elicitation_defaults",
        "arguments": {}
      }
    ],
    "hostable": true
  },
  {
    "name": "sse-retry",
    "description": "Tests that client respects SSE retry field timing and reconnects properly (SEP-1699)",
    "source": {
      "introducedIn": "2025-11-25",
      "removedIn": "2026-07-28"
    },
    "hostable": true
  },
  {
    "name": "request-metadata",
    "description": "Per-request _meta and MCP-Protocol-Version header obligations (SEP-2575)",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "",
    "hostable": true
  },
  {
    "name": "auth/metadata-default",
    "description": "Tests Basic OAuth metadata discovery flow.\n\n**PRM:** /.well-known/oauth-protected-resource/mcp\n**OAuth metadata:** /.well-known/oauth-authorization-server\n",
    "source": {
      "introducedIn": "2025-11-25"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/metadata-var1",
    "description": "Tests Basic OAuth metadata discovery flow.\n\n**PRM:** /.well-known/oauth-protected-resource/mcp (not in WWW-Authenticate)\n**OAuth metadata:** /.well-known/openid-configuration\n",
    "source": {
      "introducedIn": "2025-11-25"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/metadata-var2",
    "description": "Tests Basic OAuth metadata discovery flow.\n\n**PRM:** /.well-known/oauth-protected-resource (not in WWW-Authenticate)\n**OAuth metadata:** /.well-known/oauth-authorization-server/tenant1\n",
    "source": {
      "introducedIn": "2025-11-25"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/metadata-var3",
    "description": "Tests Basic OAuth metadata discovery flow.\n\n**PRM:** /custom/metadata/location.json\n**OAuth metadata:** /tenant1/.well-known/openid-configuration\n",
    "source": {
      "introducedIn": "2025-11-25"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/basic-cimd",
    "description": "Tests OAuth flow with Client ID Metadata Documents (SEP-991/URL-based client IDs). Server advertises client_id_metadata_document_supported=true and client should use URL as client_id instead of DCR.",
    "source": {
      "introducedIn": "2025-11-25"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/scope-from-www-authenticate",
    "description": "Tests that client uses scope parameter from WWW-Authenticate header when provided",
    "source": {
      "introducedIn": "2025-11-25"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/scope-from-scopes-supported",
    "description": "Tests that client uses all scopes from scopes_supported when scope not in WWW-Authenticate header",
    "source": {
      "introducedIn": "2025-11-25"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/scope-omitted-when-undefined",
    "description": "Tests that client omits scope parameter when scopes_supported is undefined",
    "source": {
      "introducedIn": "2025-11-25"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/scope-step-up",
    "description": "Tests that client handles step-up authentication with different scope requirements per operation",
    "source": {
      "introducedIn": "2025-11-25"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/scope-retry-limit",
    "description": "Tests that client implements retry limits to prevent infinite authorization loops on repeated 403 responses",
    "source": {
      "introducedIn": "2025-11-25"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true,
    "allowClientError": true
  },
  {
    "name": "auth/token-endpoint-auth-basic",
    "description": "Tests that client uses HTTP Basic authentication (client_secret_basic) when server only supports client_secret_basic",
    "source": {
      "introducedIn": "2025-06-18"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/token-endpoint-auth-post",
    "description": "Tests that client uses client_secret_post when server only supports client_secret_post",
    "source": {
      "introducedIn": "2025-06-18"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/token-endpoint-auth-none",
    "description": "Tests that client uses no authentication (public client) when server only supports none",
    "source": {
      "introducedIn": "2025-06-18"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/pre-registration",
    "description": "Tests OAuth flow with pre-registered client credentials. Server does not support DCR.",
    "source": {
      "introducedIn": "2025-11-25"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/2025-03-26-oauth-metadata-backcompat",
    "description": "Tests 2025-03-26 spec OAuth flow: no PRM (Protected Resource Metadata), OAuth metadata at root location",
    "source": {
      "introducedIn": "2025-03-26",
      "removedIn": "2025-06-18"
    },
    "hostable": false
  },
  {
    "name": "auth/2025-03-26-oauth-endpoint-fallback",
    "description": "Tests OAuth flow with no metadata endpoints, relying on fallback to standard OAuth endpoints at server root (2025-03-26 spec behavior)",
    "source": {
      "introducedIn": "2025-03-26",
      "removedIn": "2025-06-18"
    },
    "hostable": false
  },
  {
    "name": "auth/resource-mismatch",
    "description": "Tests that client rejects when PRM resource does not match server URL",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true,
    "allowClientError": true
  },
  {
    "name": "auth/offline-access-scope",
    "description": "Tests that a client that wants a refresh token handles offline_access scope and refresh_token grant type when AS supports them (SEP-2207)",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/offline-access-not-supported",
    "description": "Tests that client does not request offline_access when AS does not list it in scopes_supported (SEP-2207)",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/authorization-server-migration",
    "description": "Tests that a client, when the PRM authorization_servers changes to a new issuer, re-registers with the new authorization server and does not reuse credentials from the previous one (SEP-2352).",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as",
      "as2"
    ],
    "hostable": true
  },
  {
    "name": "auth/iss-supported",
    "description": "Tests that client accepts authorization response when server advertises and sends correct iss parameter",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/iss-not-advertised",
    "description": "Tests that client accepts authorization response when server does not advertise or send iss parameter",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true
  },
  {
    "name": "auth/iss-supported-missing",
    "description": "Tests that client rejects authorization response when server advertised iss support but omitted iss from redirect",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true,
    "allowClientError": true
  },
  {
    "name": "auth/iss-wrong-issuer",
    "description": "Tests that client rejects authorization response when iss does not match the authorization server issuer",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true,
    "allowClientError": true
  },
  {
    "name": "auth/iss-unexpected",
    "description": "Tests that client compares iss against recorded issuer even when not advertised, and rejects on mismatch",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true,
    "allowClientError": true
  },
  {
    "name": "auth/iss-normalized",
    "description": "Tests that client compares iss using simple string comparison without applying URL normalization",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true,
    "allowClientError": true
  },
  {
    "name": "auth/metadata-issuer-mismatch",
    "description": "Tests that client rejects authorization server metadata whose issuer does not match the issuer used to construct the well-known URL",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "auxRoles": [
      "as"
    ],
    "hostable": true,
    "allowClientError": true
  },
  {
    "name": "auth/client-credentials-jwt",
    "description": "Tests OAuth client_credentials flow with private_key_jwt authentication (SEP-1046)",
    "source": {
      "extensionId": "io.modelcontextprotocol/oauth-client-credentials"
    },
    "hostable": false
  },
  {
    "name": "auth/client-credentials-basic",
    "description": "Tests OAuth client_credentials flow with client_secret_basic authentication",
    "source": {
      "extensionId": "io.modelcontextprotocol/oauth-client-credentials"
    },
    "hostable": false
  },
  {
    "name": "auth/enterprise-managed-authorization",
    "description": "Tests complete SEP-990 flow: token exchange + JWT bearer grant (Enterprise-Managed Authorization)",
    "source": {
      "extensionId": "io.modelcontextprotocol/enterprise-managed-authorization"
    },
    "hostable": false
  },
  {
    "name": "auth/dpop",
    "description": "Tests that an MCP client requests a DPoP-bound access token (a valid DPoP proof at the token request) and presents it using the DPoP Authorization scheme (not Bearer) with a fresh, well-formed DPoP proof on each POST /mcp request, when the server does not require a nonce (SEP-1932 / RFC 9449 §5, §7.1, §4.2–4.3).",
    "source": {
      "extensionId": "io.modelcontextprotocol/auth/dpop"
    },
    "hostable": false
  },
  {
    "name": "auth/dpop-nonce",
    "description": "Tests that an MCP client, when the authorization server and MCP server require a DPoP nonce, retries the token request and the MCP request with the server-supplied nonce (RFC 9449 §8/§9) — on top of requesting a DPoP-bound token and presenting it with the DPoP Authorization scheme and a fresh proof per request (SEP-1932 / RFC 9449 §5, §7.1, §4.2–4.3).",
    "source": {
      "extensionId": "io.modelcontextprotocol/auth/dpop"
    },
    "hostable": false
  },
  {
    "name": "auth/wif-jwt-bearer",
    "description": "Tests the RFC 7523 JWT-bearer grant for workload identity federation (SEP-1933). The client must: use grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer, include the workload JWT as the assertion parameter, and surface errors (invalid_grant, invalid_scope, unauthorized_client) without retrying or switching grant types.",
    "source": {
      "extensionId": "io.modelcontextprotocol/auth/wif"
    },
    "hostable": false
  },
  {
    "name": "sep-2322-client-request-state",
    "description": "Tests client MRTR behavior: requestState echo, no-state omission, and JSON-RPC id uniqueness (SEP-2322)",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "steps": [
      {
        "op": "tools/list"
      },
      {
        "op": "tools/call",
        "name": "test_mrtr_echo_state"
      },
      {
        "op": "tools/call",
        "name": "test_mrtr_unrelated"
      },
      {
        "op": "tools/call",
        "name": "test_mrtr_no_state"
      },
      {
        "op": "tools/call",
        "name": "test_mrtr_no_result_type"
      }
    ],
    "hostable": true
  },
  {
    "name": "http-standard-headers",
    "description": "Tests that client includes Mcp-Method and Mcp-Name headers on HTTP POST requests (SEP-2243)",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "",
    "hostable": true
  },
  {
    "name": "http-custom-headers",
    "description": "Tests that client mirrors x-mcp-header tool parameters into Mcp-Param headers with correct encoding (SEP-2243)",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "",
    "steps": [
      {
        "op": "tools/list"
      },
      {
        "op": "tools/call",
        "name": "test_custom_headers",
        "arguments": {
          "region": "us-west1",
          "priority": 42,
          "verbose": false,
          "debug": true,
          "empty_val": "",
          "method_val": "test-method",
          "float_val": 3.14159,
          "non_ascii_val": "Hello, 世界",
          "whitespace_val": " padded ",
          "leading_space_val": " us-west1",
          "trailing_space_val": "us-west1 ",
          "internal_space_val": "us west 1",
          "control_char_val": "line1\nline2",
          "crlf_val": "line1\r\nline2",
          "tab_val": "\tindented",
          "query": "SELECT * FROM users"
        }
      },
      {
        "op": "tools/call",
        "name": "test_custom_headers_null",
        "arguments": {
          "region": "us-east1",
          "priority": 1,
          "verbose": null,
          "query": "SELECT 1"
        }
      }
    ],
    "hostable": true
  },
  {
    "name": "http-invalid-tool-headers",
    "description": "Tests that client rejects tools with invalid x-mcp-header annotations (SEP-2243)",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "",
    "steps": [
      {
        "op": "tools/list"
      },
      {
        "op": "tools/call",
        "name": "valid_tool",
        "arguments": {
          "region": "us-west1"
        }
      }
    ],
    "hostable": true,
    "allowClientError": true
  },
  {
    "name": "json-schema-ref-no-deref",
    "description": "Tests that a client does not automatically dereference a network-URI `$ref` in a tool's inputSchema (SEP-2106).\n\nThe scenario advertises a tool whose inputSchema contains a `$ref` pointing at a canary URL. The client should list tools (and may otherwise process the schema), but must not fetch the canary URL. Same-document refs (`#/$defs/...`) remain safe to resolve.",
    "source": {
      "introducedIn": "2026-07-28"
    },
    "mcpPath": "/mcp",
    "steps": [
      {
        "op": "tools/list"
      }
    ],
    "hostable": true
  },
  {
    "name": "json-schema-2020-12-preservation",
    "description": "Validates client-side preservation of JSON Schema 2020-12 keywords (SEP-1613, SEP-2106).\n\n**Client Implementation Requirements:**\n\n1. Call `tools/list`. The mock server advertises two tools: `json_schema_2020_12_tool` (focal, carries the rich inputSchema) and `json_schema_echo` (permissive echo).\n2. Round-trip the focal tool's `inputSchema` back via `tools/call` on `json_schema_echo`, passing it verbatim as the `schema` argument:\n\n```json\n{\n  \"name\": \"json_schema_echo\",\n  \"arguments\": {\n    \"schema\": \"<the inputSchema the client received for json_schema_2020_12_tool>\"\n  }\n}\n```\n\nThe scenario compares the echoed schema against the original fixture and flags any keyword that was stripped or altered during the client's internal parsing.\n\n**Verification**: `$schema`, `$defs`, and `additionalProperties` must be preserved (SEP-1613). The SEP-2106 vocabulary (`$anchor` inside `$defs`, composition `allOf`/`anyOf`, conditional `if`/`then`/`else`) must also survive; for dated protocol versions these checks are SKIPPED rather than FAILURE since SEP-2106 applies from the draft version.",
    "source": {
      "introducedIn": "2025-11-25"
    },
    "hostable": false
  },
  {
    "name": "sep-2640-client-no-prefetch",
    "description": "A client MUST NOT retrieve a skill file before the skill is loaded",
    "source": {
      "extensionId": "io.modelcontextprotocol/skills"
    },
    "mcpPath": "",
    "hostable": true
  },
  {
    "name": "sep-2640-client-verify-digest",
    "description": "When a host retrieves a file listed in a skill's resources, it MUST verify the content against that entry's digest, and MUST NOT use unverified content.",
    "source": {
      "extensionId": "io.modelcontextprotocol/skills"
    },
    "mcpPath": "",
    "hostable": true,
    "allowClientError": true
  },
  {
    "name": "sep-2640-client-verify-size",
    "description": "A read whose byte length differs from the entry's size is a verification failure equivalent to a digest mismatch, whether or not the host goes on to compute the digest.",
    "source": {
      "extensionId": "io.modelcontextprotocol/skills"
    },
    "mcpPath": "",
    "hostable": true,
    "allowClientError": true
  },
  {
    "name": "sep-2640-client-verify-frontmatter",
    "description": "After fetching a SKILL.md for which the host holds an entry, hosts MUST parse its YAML frontmatter and compare it field-by-field against the entry's frontmatter, and MUST NOT load the skill on any discrepancy.",
    "source": {
      "extensionId": "io.modelcontextprotocol/skills"
    },
    "mcpPath": "",
    "hostable": true,
    "allowClientError": true
  }
];
