#!/usr/bin/env -S npx tsx
/**
 * Vendor schema/{version}/schema.ts and schema/{version}/schema.json from the
 * modelcontextprotocol spec repo into src/spec-types/{version}.ts and
 * src/spec-types/{version}.schema.json at a pinned SHA, for every entry of
 * DATED_SPEC_VERSIONS plus `draft`, and regenerate src/spec-types/schemas.ts
 * (the version -> JSON Schema map the wire validator compiles).
 *
 * Publishing a new spec revision: append its date to DATED_SPEC_VERSIONS in
 * src/types.ts, then run this at the release tag. Nothing else in the schema
 * plumbing needs editing.
 *
 * Usage: npm run sync-schema -- <sha-or-ref>
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, rmSync, copyFileSync } from 'node:fs';
import { join } from 'node:path';
import { DATED_SPEC_VERSIONS, DRAFT_SPEC_VERSION } from '../src/types';

// DRAFT_SPEC_VERSION is the literal 'draft', which is also the spec repo's
// directory name for the in-progress revision.
const VERSIONS = [...DATED_SPEC_VERSIONS, DRAFT_SPEC_VERSION] as const;
const SPEC_REPO =
  'https://github.com/modelcontextprotocol/modelcontextprotocol.git';
const OUT_DIR = join(process.cwd(), 'src', 'spec-types');

const ref = process.argv[2];
if (!ref) {
  console.error('Usage: npm run sync-schema -- <sha-or-ref>');
  process.exit(1);
}

const tmp = join(process.cwd(), '.sync-schema-tmp');
rmSync(tmp, { recursive: true, force: true });
mkdirSync(tmp, { recursive: true });
mkdirSync(OUT_DIR, { recursive: true });

const git = (args: string[]) =>
  execFileSync('git', args, { cwd: tmp, encoding: 'utf8' });

/** `2025-03-26` -> `schema2025_03_26`, `draft` -> `schemaDraft`. */
function importName(v: string): string {
  return v === DRAFT_SPEC_VERSION
    ? 'schemaDraft'
    : `schema${v.replace(/-/g, '_')}`;
}

try {
  console.log(`Fetching ${SPEC_REPO} @ ${ref} ...`);
  git(['init', '-q']);
  git(['remote', 'add', 'origin', SPEC_REPO]);
  git(['fetch', '-q', '--depth', '1', 'origin', ref]);
  git(['checkout', '-q', 'FETCH_HEAD']);
  const sha = git(['rev-parse', 'HEAD']).trim();

  for (const v of VERSIONS) {
    copyFileSync(join(tmp, 'schema', v, 'schema.ts'), join(OUT_DIR, `${v}.ts`));
    console.log(`  ${v} -> src/spec-types/${v}.ts`);
    copyFileSync(
      join(tmp, 'schema', v, 'schema.json'),
      join(OUT_DIR, `${v}.schema.json`)
    );
    console.log(`  ${v} -> src/spec-types/${v}.schema.json`);
  }

  const schemasTs =
    `// Generated by scripts/sync-schema.ts from DATED_SPEC_VERSIONS + draft.\n` +
    `// Do not edit: add the version to src/types.ts and re-run the script.\n` +
    `import type { SpecVersion } from '../types';\n` +
    VERSIONS.map(
      (v) => `import ${importName(v)} from './${v}.schema.json';\n`
    ).join('') +
    `\n/** Vendored JSON Schema for every spec version the suite can target. */\n` +
    `export const SPEC_SCHEMAS: Record<SpecVersion, Record<string, unknown>> = {\n` +
    VERSIONS.map((v) => `  '${v}': ${importName(v)},\n`).join('') +
    `};\n`;
  writeFileSync(join(OUT_DIR, 'schemas.ts'), schemasTs, 'utf8');
  console.log('  version map -> src/spec-types/schemas.ts');

  writeFileSync(
    join(OUT_DIR, 'SOURCE'),
    `modelcontextprotocol@${sha}\n`,
    'utf8'
  );
  console.log(`Pinned: modelcontextprotocol@${sha}`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
