/**
 * Bundle requirements/*.yaml into a TypeScript module.
 *
 * `loadRequirements()` reads the yaml files from disk next to the package,
 * but a serverless deploy (examples/hosted/deploy-valtown.ts) stages only
 * the TypeScript import closure, so the live val has no yaml and the matrix
 * would have no columns. This script writes examples/hosted/requirements-
 * bundle.ts with the verbatim text of every requirement set; valtown.ts
 * registers it via registerRequirementSources() before building the matrix.
 *
 *   npm run hosted:bundle-requirements
 *
 * The generated file is committed; bundle-requirements.test.ts fails when it
 * drifts from the yaml files.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
export const REQUIREMENTS_DIR = resolve(SCRIPT_DIR, '../../requirements');
export const BUNDLE_PATH = join(SCRIPT_DIR, 'requirements-bundle.ts');

/** revision → verbatim yaml text, in file-name order. */
export function readRequirementSources(
  dir: string = REQUIREMENTS_DIR
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const file of readdirSync(dir)
    .filter((f) => f.endsWith('.yaml'))
    .sort()) {
    out[file.replace(/\.yaml$/, '')] = readFileSync(join(dir, file), 'utf8');
  }
  return out;
}

/** The module text: one JSON string literal per revision, nothing to escape by hand. */
export function renderBundle(sources: Record<string, string>): string {
  const entries = Object.entries(sources)
    .map(([rev, text]) => `  ${JSON.stringify(rev)}: ${JSON.stringify(text)}`)
    .join(',\n');
  return `// Generated by \`npm run hosted:bundle-requirements\` — do not edit.
// Verbatim text of requirements/*.yaml for deployments that ship the import
// closure only (see examples/hosted/valtown.ts). A test keeps it in sync.

export const REQUIREMENT_SOURCES: Record<string, string> = {
${entries}
};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const sources = readRequirementSources();
  writeFileSync(BUNDLE_PATH, renderBundle(sources));
  console.log(`wrote ${BUNDLE_PATH} (${Object.keys(sources).join(', ')})`);
}
