// Generated by scripts/sync-schema.ts from DATED_SPEC_VERSIONS + draft.
// Do not edit: add the version to src/types.ts and re-run the script.
import type { SpecVersion } from '../types';
import schema2025_03_26 from './2025-03-26.schema.json';
import schema2025_06_18 from './2025-06-18.schema.json';
import schema2025_11_25 from './2025-11-25.schema.json';
import schema2026_07_28 from './2026-07-28.schema.json';
import schemaDraft from './draft.schema.json';

/** Vendored JSON Schema for every spec version the suite can target. */
export const SPEC_SCHEMAS: Record<SpecVersion, Record<string, unknown>> = {
  '2025-03-26': schema2025_03_26,
  '2025-06-18': schema2025_06_18,
  '2025-11-25': schema2025_11_25,
  '2026-07-28': schema2026_07_28,
  'draft': schemaDraft,
};
